### ISSUE TITLE
'typeof matter' has no call signatures when exporting the site

### ISSUE THREAD

**Issue by nicu-chiciuc** [juristr/egghead-build-portfolio-with-next-tailwind-nx#1]
Hello, nice tutorial. I'm having some issues when trying to export the site.
I get the following errors:
```
❯ yarn nx export site
yarn run v1.22.17
$ /Users/nicu/Dev/nx_learn/nicusordev/node_modules/.bin/nx export site

> nx run site:export 
Failed to compile.

../../libs/markdown/src/lib/markdown.ts:13:29
Type error: This expression is not callable.
  Type 'typeof matter' has no call signatures.

  11 |   const fileContent = readFileSync(postFilePath);
  12 | 
> 13 |   const { data, content } = matter(fileContent);
     |                             ^
  14 | 
  15 |   return {
  16 |     frontMatter: data,
info  - Checking validity of types .
———————————————————————————————————————————————

>  NX   ERROR  Running target "site:export" failed

  Failed tasks:
  
  - site:export
  
  Hint: run the command with --verbose for more details.


>  NX   CLOUD  See run details at https://nx.app/runs/3qEzWSTDQPW

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
<img width="961" alt="Screenshot 2021-12-21 at 13 24 11" src="https://user-images.githubusercontent.com/4076804/146922333-41bf9d7c-38d1-46e1-9ad9-c94c21e23d70.png">

And here is my editor. I get the errors for `fs` and `path` (because `@types/node` is not setup properly I guess) but matter seems to be typed well.

I'm not very knowledgeable in how TS works when there are multiple projects so I thought maybe you've encountered this or maybe you know what steps I might take.

**Comment by juristr** [comment]
Hey,

sorry for replying late. 🤔 I had some issues with the GrayMatter library
as they changed things quite a bit over the course of recording this course
and also introduced breaking changes.
Can you try to make sure you have the exact same version as I used in the
course?
The video should have the GitHub branch linked, so you can inspect things
there.

I'm planning to schedule some time to update things, also adjust things for
the Tailwind v3 release (which released a couple days before my course
launch 🙈)

Also thanks for reaching out!
--

*👋 Juri*
JavaScript Architect & Engineering Manager  @ nrwl.io • Google Developer
Expert in Web Tech • juri.dev • @juristr <https://twitter.com/juristr>
*subscribe to my Newsletter <http://bit.ly/juri-news>*

**Comment by nicu-chiciuc** [comment]
I guess it's no big deal, a well place `any` solves all the problems 😅. Although I've noticed that TS behaves strangely when there are multiple tsconfigs/projects.

**Comment by juristr** [comment]
Yeah multiple tsconfigs shouldn't be a problem if they're well linked. I'm using those a lot. But  the graymatter lib caused various trouble in the past, so 🙂
